version: 1

tools:
  code_review:
    enabled: true
    style_guide: .gemini/styleguide.me
    # 파일 확장자별로 리뷰 룰을 다르게 적용할 수 있습니다.
    # 추후 Gemini Code Assist가 제공하는 여러 툴을 설정할 수 있습니다.

# 리뷰를 무시할 파일 또는 디렉터리 설정
# 리뷰를 무시할 파일 또는 디렉터리 설정 (React 프로젝트)
exclude:
  # 빌드 결과물 (배포용)
  - "build/"
  - "dist/"
  # 캐시, 임시 파일
  - ".cache/"
  # Node.js 패키지
  - "node_modules/"
  # 환경 변수 파일 (보안상 중요한 정보 포함 가능)
  - "**/.env"
  - "**/.env.local"
  # 기타 특정 설정/아티팩트 (사용하는 툴에 따라 추가 가능)
  - "**/coverage/" # 테스트 커버리지 보고서
  - "**/report.html" # 다른 형태의 보고서